package com.pryzmm.splitself.entity.client;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;
import org.joml.Vector3f;

public class TheForgottenAnimations {

    public static final Transformation.Interpolation STEP = (dest, delta, keyframes, start, end, scale) -> {
        Vector3f target = keyframes[start].target();
        dest.set(target.x() * scale, target.y() * scale, target.z() * scale);
        return dest;
    };


    public static final Animation ANIM_THE_FORGOTTEN_IDLE = Animation.Builder.create(4f).looping()
            .addBoneAnimation("RightArm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("LeftArm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("Head_Distort",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(0.041676664f, AnimationHelper.createTranslationalVector(-6f, 2f, 7f),
                                    STEP),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(-5f, 3f, 3f),
                                    STEP),
                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(-3f, -1f, 1f),
                                    STEP),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(-3f, 1f, 1f),
                                    STEP),
                            new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(-2f, 1f, 4f),
                                    STEP),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(-5f, 2f, -1f),
                                    STEP),
                            new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(-5f, -4f, -1f),
                                    STEP),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(-3f, -3f, -1f),
                                    STEP),
                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(-2f, -3f, 5f),
                                    STEP),
                            new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(-3f, -1f, 1f),
                                    STEP),
                            new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(-2f, 0f, -2f),
                                    STEP),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-6f, 2f, 4f),
                                    STEP),
                            new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(-3f, 0f, -1f),
                                    STEP),
                            new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(-2f, 0f, 4f),
                                    STEP),
                            new Keyframe(0.625f, AnimationHelper.createTranslationalVector(-7f, 0f, 4f),
                                    STEP),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(-5f, 1f, 4f),
                                    STEP),
                            new Keyframe(0.7083434f, AnimationHelper.createTranslationalVector(-3.5f, 2f, 3f),
                                    STEP),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(-6.5f, -4f, 3f),
                                    STEP),
                            new Keyframe(0.7916766f, AnimationHelper.createTranslationalVector(-2.5f, -2f, 3f),
                                    STEP),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(-5.5f, 1f, 3f),
                                    STEP),
                            new Keyframe(0.875f, AnimationHelper.createTranslationalVector(-2.5f, -2f, -1f),
                                    STEP),
                            new Keyframe(0.9167666f, AnimationHelper.createTranslationalVector(-6.5f, -2f, 4f),
                                    STEP),
                            new Keyframe(0.9583434f, AnimationHelper.createTranslationalVector(-0.5f, -2f, 3f),
                                    STEP),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(1.0416767f, AnimationHelper.createTranslationalVector(-6f, 2f, 3f),
                                    STEP),
                            new Keyframe(1.0834333f, AnimationHelper.createTranslationalVector(-5f, 3f, 3f),
                                    STEP),
                            new Keyframe(1.125f, AnimationHelper.createTranslationalVector(-3f, -1f, 1f),
                                    STEP),
                            new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(-3f, 1f, 1f),
                                    STEP),
                            new Keyframe(1.2083433f, AnimationHelper.createTranslationalVector(-2f, 1f, 4f),
                                    STEP),
                            new Keyframe(1.25f, AnimationHelper.createTranslationalVector(-5f, 2f, -1f),
                                    STEP),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(-5f, -4f, -1f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(-3f, -3f, -1f),
                                    STEP),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(-2f, -3f, 5f),
                                    STEP),
                            new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(-6f, -4f, 5f),
                                    STEP),
                            new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(-2f, 0f, -2f),
                                    STEP),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(-6f, 2f, 5f),
                                    STEP),
                            new Keyframe(1.5416767f, AnimationHelper.createTranslationalVector(-3f, 0f, -1f),
                                    STEP),
                            new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(-2f, 0f, 4f),
                                    STEP),
                            new Keyframe(1.625f, AnimationHelper.createTranslationalVector(-7f, 0f, 4f),
                                    STEP),
                            new Keyframe(1.6766667f, AnimationHelper.createTranslationalVector(-5f, 1f, 4f),
                                    STEP),
                            new Keyframe(1.7083433f, AnimationHelper.createTranslationalVector(-3.5f, 2f, 3f),
                                    STEP),
                            new Keyframe(1.75f, AnimationHelper.createTranslationalVector(4.5f, 2f, -6f),
                                    STEP),
                            new Keyframe(1.7916767f, AnimationHelper.createTranslationalVector(1.5f, 0f, -6f),
                                    STEP),
                            new Keyframe(1.8343333f, AnimationHelper.createTranslationalVector(-5.5f, 1f, 3f),
                                    STEP),
                            new Keyframe(1.875f, AnimationHelper.createTranslationalVector(0.5f, -2f, -4f),
                                    STEP),
                            new Keyframe(1.9167667f, AnimationHelper.createTranslationalVector(-6.5f, -2f, 4f),
                                    STEP),
                            new Keyframe(1.9583433f, AnimationHelper.createTranslationalVector(-0.5f, -2f, 3f),
                                    STEP),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(2.0416765f, AnimationHelper.createTranslationalVector(-6f, 2f, 7f),
                                    STEP),
                            new Keyframe(2.0834335f, AnimationHelper.createTranslationalVector(-5f, 3f, 3f),
                                    STEP),
                            new Keyframe(2.125f, AnimationHelper.createTranslationalVector(-3f, -1f, 1f),
                                    STEP),
                            new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(-3f, 1f, 1f),
                                    STEP),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(-2f, 1f, 4f),
                                    STEP),
                            new Keyframe(2.25f, AnimationHelper.createTranslationalVector(-5f, 2f, -1f),
                                    STEP),
                            new Keyframe(2.2916765f, AnimationHelper.createTranslationalVector(-5f, -4f, -1f),
                                    STEP),
                            new Keyframe(2.3433335f, AnimationHelper.createTranslationalVector(-3f, -3f, -1f),
                                    STEP),
                            new Keyframe(2.375f, AnimationHelper.createTranslationalVector(-2f, -3f, 5f),
                                    STEP),
                            new Keyframe(2.4167665f, AnimationHelper.createTranslationalVector(-6f, -4f, 5f),
                                    STEP),
                            new Keyframe(2.4583435f, AnimationHelper.createTranslationalVector(-2f, 0f, -2f),
                                    STEP),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(-6f, 2f, 5f),
                                    STEP),
                            new Keyframe(2.5416765f, AnimationHelper.createTranslationalVector(-3f, 0f, -1f),
                                    STEP),
                            new Keyframe(2.5834335f, AnimationHelper.createTranslationalVector(-2f, 0f, 4f),
                                    STEP),
                            new Keyframe(2.625f, AnimationHelper.createTranslationalVector(-7f, 0f, 4f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createTranslationalVector(-5f, 1f, 4f),
                                    STEP),
                            new Keyframe(2.7083435f, AnimationHelper.createTranslationalVector(-3.5f, 2f, 3f),
                                    STEP),
                            new Keyframe(2.75f, AnimationHelper.createTranslationalVector(-6.5f, -4f, 3f),
                                    STEP),
                            new Keyframe(2.7916765f, AnimationHelper.createTranslationalVector(-2.5f, -2f, 3f),
                                    STEP),
                            new Keyframe(2.8343335f, AnimationHelper.createTranslationalVector(-5.5f, 1f, 3f),
                                    STEP),
                            new Keyframe(2.875f, AnimationHelper.createTranslationalVector(-2.5f, -2f, -1f),
                                    STEP),
                            new Keyframe(2.9167665f, AnimationHelper.createTranslationalVector(-6.5f, -2f, 4f),
                                    STEP),
                            new Keyframe(2.9583435f, AnimationHelper.createTranslationalVector(-0.5f, -2f, 3f),
                                    STEP),
                            new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    STEP),
                            new Keyframe(3.0416765f, AnimationHelper.createTranslationalVector(-6f, 2f, 4f),
                                    STEP),
                            new Keyframe(3.0834335f, AnimationHelper.createTranslationalVector(-5f, 3f, 3f),
                                    STEP),
                            new Keyframe(3.125f, AnimationHelper.createTranslationalVector(-3f, -1f, 1f),
                                    STEP),
                            new Keyframe(3.1676665f, AnimationHelper.createTranslationalVector(-3f, 1f, 1f),
                                    STEP),
                            new Keyframe(3.2083435f, AnimationHelper.createTranslationalVector(-2f, 1f, 4f),
                                    STEP),
                            new Keyframe(3.25f, AnimationHelper.createTranslationalVector(-5f, 2f, -1f),
                                    STEP),
                            new Keyframe(3.2916765f, AnimationHelper.createTranslationalVector(-5f, -4f, -1f),
                                    STEP),
                            new Keyframe(3.3433335f, AnimationHelper.createTranslationalVector(-3f, -3f, -1f),
                                    STEP),
                            new Keyframe(3.375f, AnimationHelper.createTranslationalVector(-2f, -3f, 5f),
                                    STEP),
                            new Keyframe(3.4167665f, AnimationHelper.createTranslationalVector(-6f, -4f, 5f),
                                    STEP),
                            new Keyframe(3.4583435f, AnimationHelper.createTranslationalVector(-2f, 0f, -2f),
                                    STEP),
                            new Keyframe(3.5f, AnimationHelper.createTranslationalVector(-6f, 2f, 5f),
                                    STEP),
                            new Keyframe(3.5416765f, AnimationHelper.createTranslationalVector(-3f, 0f, -1f),
                                    STEP),
                            new Keyframe(3.5834335f, AnimationHelper.createTranslationalVector(-2f, 0f, 4f),
                                    STEP),
                            new Keyframe(3.625f, AnimationHelper.createTranslationalVector(-7f, 0f, 4f),
                                    STEP),
                            new Keyframe(3.6766665f, AnimationHelper.createTranslationalVector(-5f, 1f, 4f),
                                    STEP),
                            new Keyframe(3.7083435f, AnimationHelper.createTranslationalVector(-3.5f, 2f, 3f),
                                    STEP),
                            new Keyframe(3.75f, AnimationHelper.createTranslationalVector(-6.5f, -4f, 3f),
                                    STEP),
                            new Keyframe(3.7916765f, AnimationHelper.createTranslationalVector(-2.5f, -2f, 3f),
                                    STEP),
                            new Keyframe(3.8343335f, AnimationHelper.createTranslationalVector(-5.5f, 1f, 3f),
                                    STEP),
                            new Keyframe(3.875f, AnimationHelper.createTranslationalVector(-2.5f, -2f, -1f),
                                    STEP),
                            new Keyframe(3.9167665f, AnimationHelper.createTranslationalVector(-6.5f, -2f, 4f),
                                    STEP),
                            new Keyframe(3.9583435f, AnimationHelper.createTranslationalVector(-0.5f, -2f, 3f),
                                    STEP)))
            .addBoneAnimation("Head_Distort",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 7.5f, 0f),
                                    STEP),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(0f, -25f, 0f),
                                    STEP),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(0f, 30f, 0f),
                                    STEP),
                            new Keyframe(0.20834334f, AnimationHelper.createRotationalVector(37.5f, -25f, 0f),
                                    STEP),
                            new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(5f, -25f, 0f),
                                    STEP),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(7.26f, -13.72f, -14.22f),
                                    STEP),
                            new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(-1.28f, 20.31f, -24.54f),
                                    STEP),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(13.15f, 15.67f, 20f),
                                    STEP),
                            new Keyframe(0.5834334f, AnimationHelper.createRotationalVector(-19.35f, 15.67f, 20f),
                                    STEP),
                            new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(33.15f, 15.67f, 20f),
                                    STEP),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(-16.85f, 15.67f, 20f),
                                    STEP),
                            new Keyframe(0.7916766f, AnimationHelper.createRotationalVector(10.65f, 15.67f, 20f),
                                    STEP),
                            new Keyframe(0.875f, AnimationHelper.createRotationalVector(-36.85f, 15.67f, 20f),
                                    STEP),
                            new Keyframe(0.9583434f, AnimationHelper.createRotationalVector(10.82f, -6.32f, -7.5f),
                                    STEP),
                            new Keyframe(1.0416767f, AnimationHelper.createRotationalVector(13.37f, 8.42f, -4.68f),
                                    STEP),
                            new Keyframe(1.0834333f, AnimationHelper.createRotationalVector(15.53f, 2.74f, 17.2f),
                                    STEP),
                            new Keyframe(1.2083433f, AnimationHelper.createRotationalVector(20f, 38.59f, 29.23f),
                                    STEP),
                            new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(-10f, 38.59f, 29.23f),
                                    STEP),
                            new Keyframe(1.375f, AnimationHelper.createRotationalVector(-3.88f, 41.66f, -3.41f),
                                    STEP),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(23.68f, 24.85f, 38.82f),
                                    STEP),
                            new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(-8.82f, 24.85f, 38.82f),
                                    STEP),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-157.86f, -1.88f, -177.15f),
                                    STEP),
                            new Keyframe(1.7916767f, AnimationHelper.createRotationalVector(-82.74f, 67.69f, -78.55f),
                                    STEP),
                            new Keyframe(1.875f, AnimationHelper.createRotationalVector(-43.4f, 56.76f, -34.72f),
                                    STEP),
                            new Keyframe(1.9167667f, AnimationHelper.createRotationalVector(-23.68f, 20.34f, -5.05f),
                                    STEP),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-7.25f, 30.05f, 32.31f),
                                    STEP),
                            new Keyframe(2.0834335f, AnimationHelper.createRotationalVector(22.03f, 22.13f, 93.62f),
                                    STEP),
                            new Keyframe(2.1676665f, AnimationHelper.createRotationalVector(-4.34f, 30.55f, 38.07f),
                                    STEP),
                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(-1.35f, -29.19f, 45.24f),
                                    STEP),
                            new Keyframe(2.3433335f, AnimationHelper.createRotationalVector(-66.03f, 43.99f, -41.29f),
                                    STEP),
                            new Keyframe(2.4167665f, AnimationHelper.createRotationalVector(-14.67f, 61.46f, 26.52f),
                                    STEP),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(23.09f, 58.6f, 72.19f),
                                    STEP),
                            new Keyframe(2.5834335f, AnimationHelper.createRotationalVector(0.59f, 58.6f, 72.19f),
                                    STEP),
                            new Keyframe(2.625f, AnimationHelper.createRotationalVector(-49.02f, 37.4f, 9.32f),
                                    STEP),
                            new Keyframe(2.7083435f, AnimationHelper.createRotationalVector(0.59f, 58.6f, 72.19f),
                                    STEP),
                            new Keyframe(2.75f, AnimationHelper.createRotationalVector(-107.36f, 78.61f, -50.26f),
                                    STEP),
                            new Keyframe(2.8343335f, AnimationHelper.createRotationalVector(-2.71f, 72.19f, 89.33f),
                                    STEP),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(-71.18f, 38.84f, -24.73f),
                                    STEP),
                            new Keyframe(3.0416765f, AnimationHelper.createRotationalVector(5.77f, 25.28f, 57.04f),
                                    STEP),
                            new Keyframe(3.125f, AnimationHelper.createRotationalVector(68.01f, 84.38f, 122.48f),
                                    STEP),
                            new Keyframe(3.2083435f, AnimationHelper.createRotationalVector(88.01f, 84.38f, 122.48f),
                                    STEP),
                            new Keyframe(3.2916765f, AnimationHelper.createRotationalVector(-6.53f, 44.43f, 24.55f),
                                    STEP),
                            new Keyframe(3.3433335f, AnimationHelper.createRotationalVector(-40.45f, 21.21f, -33.17f),
                                    STEP),
                            new Keyframe(3.375f, AnimationHelper.createRotationalVector(12.26f, 58.06f, 25.63f),
                                    STEP),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(12.52f, 34.42f, 32.7f),
                                    STEP),
                            new Keyframe(3.5834335f, AnimationHelper.createRotationalVector(-16.13f, 41.73f, 34.87f),
                                    STEP),
                            new Keyframe(3.6766665f, AnimationHelper.createRotationalVector(-12.4f, 15.03f, 42.51f),
                                    STEP),
                            new Keyframe(3.7083435f, AnimationHelper.createRotationalVector(5.23f, 12.59f, 43.06f),
                                    STEP),
                            new Keyframe(3.8343335f, AnimationHelper.createRotationalVector(-14.77f, 12.59f, 43.06f),
                                    STEP),
                            new Keyframe(3.875f, AnimationHelper.createRotationalVector(-38.97f, -3.71f, -7.18f),
                                    STEP),
                            new Keyframe(3.9167665f, AnimationHelper.createRotationalVector(1.03f, -3.71f, -7.18f),
                                    STEP)))
            .addBoneAnimation("Head_Distort",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(0.041676664f, AnimationHelper.createScalingVector(0.8f, 0.5f, 1.4f),
                                    STEP),
                            new Keyframe(0.08343333f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(0.16766666f, AnimationHelper.createScalingVector(0.5f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(0.20834334f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(0.2916767f, AnimationHelper.createScalingVector(0.4f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(0.3433333f, AnimationHelper.createScalingVector(1.2f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(0.4167667f, AnimationHelper.createScalingVector(1.2f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(0.5f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(0.5834334f, AnimationHelper.createScalingVector(0.5f, 0.9f, 2f),
                                    STEP),
                            new Keyframe(0.625f, AnimationHelper.createScalingVector(1.7f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(0.6766666f, AnimationHelper.createScalingVector(1.1f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(0.7083434f, AnimationHelper.createScalingVector(0.9f, 0.4f, 1.2f),
                                    STEP),
                            new Keyframe(0.75f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(0.7916766f, AnimationHelper.createScalingVector(0.8f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(0.8343334f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(0.875f, AnimationHelper.createScalingVector(0.8f, 1.3f, 1.2f),
                                    STEP),
                            new Keyframe(0.9167666f, AnimationHelper.createScalingVector(1.2f, 1.3f, 1.5f),
                                    STEP),
                            new Keyframe(0.9583434f, AnimationHelper.createScalingVector(0.7f, 1.3f, 1.2f),
                                    STEP),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(1.0416767f, AnimationHelper.createScalingVector(0.8f, 0.5f, 1.4f),
                                    STEP),
                            new Keyframe(1.0834333f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(1.1676667f, AnimationHelper.createScalingVector(0.5f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(1.2083433f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(1.2916767f, AnimationHelper.createScalingVector(0.4f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(1.3433333f, AnimationHelper.createScalingVector(1.2f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(1.4167667f, AnimationHelper.createScalingVector(1.2f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(1.5f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(1.5834333f, AnimationHelper.createScalingVector(0.5f, 0.9f, 2f),
                                    STEP),
                            new Keyframe(1.625f, AnimationHelper.createScalingVector(1.7f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(1.6766667f, AnimationHelper.createScalingVector(1.1f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(1.7083433f, AnimationHelper.createScalingVector(0.9f, 0.4f, 1.2f),
                                    STEP),
                            new Keyframe(1.75f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(1.7916767f, AnimationHelper.createScalingVector(0.8f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(1.8343333f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(1.875f, AnimationHelper.createScalingVector(0.8f, 1.3f, 1.2f),
                                    STEP),
                            new Keyframe(1.9167667f, AnimationHelper.createScalingVector(1.2f, 1.3f, 1.5f),
                                    STEP),
                            new Keyframe(1.9583433f, AnimationHelper.createScalingVector(0.7f, 1.3f, 1.2f),
                                    STEP),
                            new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(2.0416765f, AnimationHelper.createScalingVector(0.8f, 0.5f, 1.4f),
                                    STEP),
                            new Keyframe(2.0834335f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(2.1676665f, AnimationHelper.createScalingVector(0.5f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(2.2083435f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(2.2916765f, AnimationHelper.createScalingVector(0.4f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(2.3433335f, AnimationHelper.createScalingVector(1.2f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(2.4167665f, AnimationHelper.createScalingVector(1.2f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(2.5f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(2.5834335f, AnimationHelper.createScalingVector(0.5f, 0.9f, 2f),
                                    STEP),
                            new Keyframe(2.625f, AnimationHelper.createScalingVector(1.7f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(2.6766665f, AnimationHelper.createScalingVector(1.1f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(2.7083435f, AnimationHelper.createScalingVector(0.9f, 0.4f, 1.2f),
                                    STEP),
                            new Keyframe(2.75f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(2.7916765f, AnimationHelper.createScalingVector(0.8f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(2.8343335f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(2.875f, AnimationHelper.createScalingVector(0.8f, 1.3f, 1.2f),
                                    STEP),
                            new Keyframe(2.9167665f, AnimationHelper.createScalingVector(1.2f, 1.3f, 1.5f),
                                    STEP),
                            new Keyframe(2.9583435f, AnimationHelper.createScalingVector(0.7f, 1.3f, 1.2f),
                                    STEP),
                            new Keyframe(3f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    STEP),
                            new Keyframe(3.0416765f, AnimationHelper.createScalingVector(0.8f, 0.5f, 1.4f),
                                    STEP),
                            new Keyframe(3.0834335f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(3.1676665f, AnimationHelper.createScalingVector(0.5f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(3.2083435f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(3.2916765f, AnimationHelper.createScalingVector(0.4f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(3.3433335f, AnimationHelper.createScalingVector(1.2f, 1.4f, 0.9f),
                                    STEP),
                            new Keyframe(3.4167665f, AnimationHelper.createScalingVector(1.2f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(3.5f, AnimationHelper.createScalingVector(1f, 0.9f, 0.9f),
                                    STEP),
                            new Keyframe(3.5834335f, AnimationHelper.createScalingVector(0.5f, 0.9f, 2f),
                                    STEP),
                            new Keyframe(3.625f, AnimationHelper.createScalingVector(1.7f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(3.6766665f, AnimationHelper.createScalingVector(1.1f, 0.9f, 1.4f),
                                    STEP),
                            new Keyframe(3.7083435f, AnimationHelper.createScalingVector(0.9f, 0.4f, 1.2f),
                                    STEP),
                            new Keyframe(3.75f, AnimationHelper.createScalingVector(1.1f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(3.7916765f, AnimationHelper.createScalingVector(0.8f, 1.1f, 1.2f),
                                    STEP),
                            new Keyframe(3.8343335f, AnimationHelper.createScalingVector(0.8f, 0.9f, 1.2f),
                                    STEP),
                            new Keyframe(3.875f, AnimationHelper.createScalingVector(0.8f, 1.3f, 1.2f),
                                    STEP),
                            new Keyframe(3.9167665f, AnimationHelper.createScalingVector(1.2f, 1.3f, 1.5f),
                                    STEP),
                            new Keyframe(3.9583435f, AnimationHelper.createScalingVector(0.7f, 1.3f, 1.2f),
                                    STEP))).build();
}