package com.pryzmm.splitself.config;

import java.util.ArrayList;
import java.util.List;

public record VoskModel(String ID, int size) {
    public static final List<VoskModel> voskModels = new ArrayList<>();
    static {
        voskModels.add(new VoskModel("vosk-model-small-en-us-0.15", 40));
        voskModels.add(new VoskModel("vosk-model-en-us-0.21", 1600));
        voskModels.add(new VoskModel("vosk-model-en-us-0.22", 1800));
        voskModels.add(new VoskModel("vosk-model-en-us-0.22-lgraph", 128));
        voskModels.add(new VoskModel("vosk-model-en-us-0.42-gigaspeech", 2300));
        voskModels.add(new VoskModel("vosk-model-en-us-daanzu-20200905", 1000));
        voskModels.add(new VoskModel("vosk-model-en-us-daanzu-20200905-lgraph", 129));
        voskModels.add(new VoskModel("vosk-model-en-us-librispeech-0.2", 845));
        voskModels.add(new VoskModel("vosk-model-small-en-us-zamia-0.5", 49));
        voskModels.add(new VoskModel("vosk-model-en-us-aspire-0.2", 1400));
        voskModels.add(new VoskModel("vosk-model-en-in-0.5", 1000));
        voskModels.add(new VoskModel("vosk-model-small-en-in-0.4", 36));
        voskModels.add(new VoskModel("vosk-model-small-cn-0.22", 42));
        voskModels.add(new VoskModel("vosk-model-cn-0.22", 1300));
        voskModels.add(new VoskModel("vosk-model-cn-kaldi-multicn-0.15", 1500));
        voskModels.add(new VoskModel("vosk-model-ru-0.42", 1800));
        voskModels.add(new VoskModel("vosk-model-small-ru-0.22", 45));
        voskModels.add(new VoskModel("vosk-model-ru-0.10", 2500));
        voskModels.add(new VoskModel("vosk-model-ru-0.22", 1500));
        voskModels.add(new VoskModel("vosk-model-small-fr-0.22", 41));
        voskModels.add(new VoskModel("vosk-model-fr-0.22", 1400));
        voskModels.add(new VoskModel("vosk-model-small-fr-pguyot-0.3", 39));
        voskModels.add(new VoskModel("vosk-model-fr-0.6-linto-2.2.0", 1500));
        voskModels.add(new VoskModel("vosk-model-de-0.21", 1900));
        voskModels.add(new VoskModel("vosk-model-de-tuda-0.6-900k", 4400));
        voskModels.add(new VoskModel("vosk-model-small-de-zamia-0.3", 49));
        voskModels.add(new VoskModel("vosk-model-small-de-0.15", 45));
        voskModels.add(new VoskModel("vosk-model-small-es-0.42", 39));
        voskModels.add(new VoskModel("vosk-model-es-0.42", 1400));
        voskModels.add(new VoskModel("vosk-model-small-pt-0.3", 31));
        voskModels.add(new VoskModel("vosk-model-pt-fb-v0.1.1-20220516_2113", 1600));
        voskModels.add(new VoskModel("vosk-model-el-gr-0.7", 1100));
        voskModels.add(new VoskModel("vosk-model-small-tr-0.3", 35));
        voskModels.add(new VoskModel("vosk-model-small-vn-0.4", 32));
        voskModels.add(new VoskModel("vosk-model-vn-0.4", 78));
        voskModels.add(new VoskModel("vosk-model-small-it-0.22", 48));
        voskModels.add(new VoskModel("vosk-model-it-0.22", 1200));
        voskModels.add(new VoskModel("vosk-model-small-nl-0.22", 39));
        voskModels.add(new VoskModel("vosk-model-nl-spraakherkenning-0.6", 860));
        voskModels.add(new VoskModel("vosk-model-nl-spraakherkenning-0.6-lgraph", 100));
        voskModels.add(new VoskModel("vosk-model-small-ca-0.4", 42));
        voskModels.add(new VoskModel("vosk-model-ar-mgb2-0.4", 318));
        voskModels.add(new VoskModel("vosk-model-ar-0.22-linto-1.1.0", 1300));
        voskModels.add(new VoskModel("vosk-model-small-ar-tn-0.1-linto", 158));
        voskModels.add(new VoskModel("vosk-model-ar-tn-0.1-linto", 517));
        voskModels.add(new VoskModel("vosk-model-fa-0.42", 1600));
        voskModels.add(new VoskModel("vosk-model-small-fa-0.42", 53));
        voskModels.add(new VoskModel("vosk-model-fa-0.5", 1000));
        voskModels.add(new VoskModel("vosk-model-small-fa-0.5", 60));
        voskModels.add(new VoskModel("vosk-model-tl-ph-generic-0.6", 320));
        voskModels.add(new VoskModel("vosk-model-small-uk-v3-nano", 73));
        voskModels.add(new VoskModel("vosk-model-small-uk-v3-small", 133));
        voskModels.add(new VoskModel("vosk-model-uk-v3", 343));
        voskModels.add(new VoskModel("vosk-model-uk-v3-lgraph", 325));
        voskModels.add(new VoskModel("vosk-model-small-kz-0.42", 58));
        voskModels.add(new VoskModel("vosk-model-kz-0.42", 1300));
        voskModels.add(new VoskModel("vosk-model-small-sv-rhasspy-0.15", 289));
        voskModels.add(new VoskModel("vosk-model-small-ja-0.22", 48));
        voskModels.add(new VoskModel("vosk-model-ja-0.22", 1000));
        voskModels.add(new VoskModel("vosk-model-small-eo-0.42", 42));
        voskModels.add(new VoskModel("vosk-model-small-hi-0.22", 42));
        voskModels.add(new VoskModel("vosk-model-hi-0.22", 1500));
        voskModels.add(new VoskModel("vosk-model-small-cs-0.4-rhasspy", 44));
        voskModels.add(new VoskModel("vosk-model-small-pl-0.22", 50));
        voskModels.add(new VoskModel("vosk-model-small-uz-0.22", 49));
        voskModels.add(new VoskModel("vosk-model-small-ko-0.22", 82));
        voskModels.add(new VoskModel("vosk-model-br-0.8", 70));
        voskModels.add(new VoskModel("vosk-model-gu-0.42", 700));
        voskModels.add(new VoskModel("vosk-model-small-gu-0.42", 100));
        voskModels.add(new VoskModel("vosk-model-tg-0.22", 327));
        voskModels.add(new VoskModel("vosk-model-small-tg-0.22", 50));
        voskModels.add(new VoskModel("vosk-model-small-te-0.42", 58));
        voskModels.add(new VoskModel("vosk-model-small-ky-0.42", 49));
        voskModels.add(new VoskModel("vosk-model-ky-0.42", 1100));
        voskModels.add(new VoskModel("vosk-model-small-ka-0.42", 45));
        voskModels.add(new VoskModel("vosk-model-ka-0.42", 700));
    }
}